name: Cypress Tests and S3 Deployment

on:
  push:
    branches:
      - main

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and run live-server
        run: |
          npm install
          npx live-server &

      - name: Wait for live-server to start
        run: sleep 10

      - name: Run Cypress tests
        run: npx cypress run
